{"name": "test_login_with_wrong_password", "status": "broken", "statusDetails": {"message": "KeyError: 'id'", "trace": "self = <allure_commons._allure.fixture object at 0x000002D1CC1438C0>, args = (), kwargs = {}\n\n    def __call__(self, *args, **kwargs):\n        self.parameters = func_parameters(self._fixture_function, *args, **kwargs)\n    \n        with self:\n>           return self._fixture_function(*args, **kwargs)\n\n.venv\\Lib\\site-packages\\allure_commons\\_allure.py:221: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    @pytest.fixture()\n    def courier():\n        payload = helpers.create_new_courier_and_return_login_password()\n        yield payload\n        login = requests.post(f'{urls.BASE_URL}{urls.COURIER_URL}', data=payload)\n>       id_courier = login.json()[\"id\"]\nE       KeyError: 'id'\n\nconftest.py:12: KeyError"}, "description": "Тест на авторизацию курьера с неверным паролем", "steps": [{"name": "Метод для авторизации курьера с неправильным паролем", "status": "passed", "parameters": [{"name": "password", "value": "'123456'"}], "start": 1734203359238, "stop": 1734203359542}], "start": 1734203359238, "stop": 1734203359543, "uuid": "e4757c6a-2621-4509-b8c1-aee7d1f97bb9", "historyId": "3ca7173b76b8ad616e9a805368d056e9", "testCaseId": "3ca7173b76b8ad616e9a805368d056e9", "fullName": "tests.test_login_courier.TestLogin#test_login_with_wrong_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "toshiba"}, {"name": "thread", "value": "5728-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}